version: "3.8"

services:
  app:
    build: .
    container_name: desafioserasa-app
    ports:
      - "8085:8085"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=secrety-key
    networks:
      - serasa-network

  redis:
    image: redis:7.2-alpine
    container_name: desafioserasa-redis
    ports:
      - "6379:6379"
    networks:
      - serasa-network

networks:
  serasa-network:
    driver: bridge
