name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    name: Build, Test, Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Resolver dependências
        run: mvn dependency:go-offline

      - name: Compilar aplicação
        run: mvn compile

      - name: Executar testes
        run: mvn test

      - name: Build Docker image
        run: docker build -t desafioserasa-app .
